name: maptoposter

services:
  maptoposter:
    build:
      # Hier deinen eigenen GitHub-Repo-Link eintragen, Format: https://github.com/<user>/<repo>.git#<branch>
      context: https://github.com/MaxFinix/maptoposter-docker.git#main
      dockerfile: Dockerfile
    container_name: maptoposter
    restart: unless-stopped
    user: "99:100"
    ports:
      - "6641:8000"
    environment:
      APP_HOST: 0.0.0.0
      APP_PORT: 8000
      MPLBACKEND: Agg
      MPLCONFIGDIR: /app/data/cache/matplotlib
      POSTERS_DIR: /app/data/posters
      CACHE_DIR: /app/data/cache
      FONTS_CACHE_DIR: /app/data/fonts-cache
    volumes:
      - /mnt/user/appdata/maptoposter/posters:/app/data/posters
      - /mnt/user/appdata/maptoposter/cache:/app/data/cache
      - /mnt/user/appdata/maptoposter/fonts-cache:/app/data/fonts-cache
